CREATE OR REPLACE PROCEDURE ADD_CAST(MID IN NUMBER, ANAME IN VARCHAR2, CNAME IN VARCHAR2)
IS
MOVIEID NUMBER ;
AID NUMBER ;
BEGIN
-- CHECK EXISTENSE OF ACTOR
SELECT ACTOR_ID INTO AID
FROM ACTOR
WHERE "NAME" = ANAME ;

-- CHECK EXISTENSE OF MOVIE
SELECT MOVIE_ID INTO MOVIEID
FROM MOVIE
WHERE MOVIE_ID = MID;

-- ADD INTO ACTOR_LIST
INSERT INTO ACTOR_LIST VALUES(MOVIEID, AID, CNAME);

EXCEPTION

WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('Nothing found.');
WHEN TOO_MANY_ROWS THEN
DBMS_OUTPUT.PUT_LINE('More than one found.') ;
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Some unknown error occurred.') ;

END ;
/