CREATE OR REPLACE TRIGGER DUPLICATE_CHECK
BEFORE INSERT
ON MOVIE
FOR EACH ROW
DECLARE
NEW_MOVIE_NAME VARCHAR2(50);
NEW_MOVIE_REL_DATE DATE;
OLD_MOVIE_ID NUMBER;
EXCEPTION_DUPLICATE_MOVIE EXCEPTION;
BEGIN
NEW_MOVIE_NAME := :NEW.MOVIE_NAME ;
NEW_MOVIE_REL_DATE := :NEW.RELEASE_DATE;

OLD_MOVIE_ID := 0;

SELECT COUNT(MOVIE_ID) INTO OLD_MOVIE_ID
FROM MOVIE
WHERE MOVIE_NAME = NEW_MOVIE_NAME AND NEW_MOVIE_REL_DATE = RELEASE_DATE;

--DBMS_OUTPUT.PUT_LINE('Duplicate movie id with ' || OLD_MOVIE_ID) ;

IF OLD_MOVIE_ID <> 0 THEN
  RAISE EXCEPTION_DUPLICATE_MOVIE;
END IF;


END ;
/
