CREATE OR REPLACE FUNCTION GET_NUM_MOVIES_ACTOR(ANAME IN VARCHAR2) RETURN NUMBER 
IS
NUM_MOVIES NUMBER;
BEGIN
SELECT COUNT(AL.MOVIE_ID) INTO NUM_MOVIES
FROM ACTOR_LIST AL JOIN ACTOR A USING(ACTOR_ID)
WHERE A.NAME = ANAME;

RETURN NUM_MOVIES; 

EXCEPTION

WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('Nothing found.');
WHEN TOO_MANY_ROWS THEN
DBMS_OUTPUT.PUT_LINE('More than one found.') ;
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Some unknown error occurred.') ;

END ;
/