CREATE OR REPLACE PROCEDURE GET_AVG_RATING(MID IN NUMBER, AVG_RATING OUT NUMBER)
IS
--JDATE DATE ;
--YEARS NUMBER ;
BEGIN
SELECT "AVG"(RATING) INTO AVG_RATING
FROM USER_MOVIE_RATING
WHERE MOVIE_ID = MID ;

EXCEPTION

WHEN NO_DATA_FOUND THEN
AVG_RATING := 0;
DBMS_OUTPUT.PUT_LINE('Nothing found.');
WHEN TOO_MANY_ROWS THEN
DBMS_OUTPUT.PUT_LINE('More than one found.') ;
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Some unknown error occurred.') ;

END ;
/