CREATE OR REPLACE TRIGGER UPDATE_RATING
BEFORE UPDATE
OF RATING
ON MOVIE
FOR EACH ROW

DECLARE
MOVIE_ROW MOVIE%ROWTYPE;
USER_RATING NUMBER;
OLD_RATING NUMBER;
NEW_RATING NUMBER;
OLD_MID NUMBER;

BEGIN
DBMS_OUTPUT.PUT_LINE('TRIGGER CALLED');
USER_RATING := :NEW.RATING ;
OLD_RATING := :OLD.RATING;
OLD_MID := :OLD.MOVIE_ID;
NEW_RATING := 0.1 * USER_RATING + 0.9 * OLD_RATING;
DBMS_OUTPUT.PUT_LINE('.........'|| NEW_RATING);

DBMS_OUTPUT.PUT_LINE('USER_RATING: ' || USER_RATING || 'OLD_RATING: ' || OLD_RATING);


	:NEW.RATING := NEW_RATING;

END ;
/
